### ISSUE TITLE
Performing Test HAVE_REPORT_VLINKCOLLIDING_PAIR - Failed & Compile error

### ISSUE THREAD

**Issue by Softwaretom007** [personalrobotics/or_fcl#17] opened 2016-03-31 08:08 UTC
Hi,
i try to install this collision plugin.
So,first I install libccd, then octomap and then fcl library. Everything fine.
But when I try to install or_fcl, i´ve got error:

> `Scanning dependencies of target or_fcl_plugin
> [ 50%] Building CXX object CMakeFiles/or_fcl_plugin.dir/src/or_fcl_plugin.cpp.o
> [100%] Building CXX object CMakeFiles/or_fcl_plugin.dir/src/FCLCollisionChecker.cpp.o
> /home/tomas/or_fcl/src/FCLCollisionChecker.cpp: In static member function ‘static bool or_fcl::FCLCollisionChecker::NarrowPhaseCheckCollision(fcl::CollisionObject*, fcl::CollisionObject*, void*)’:
> /home/tomas/or_fcl/src/FCLCollisionChecker.cpp:847:74: error: no matching function for call to ‘std::vector<std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> > >::push_back(OpenRAVE::KinBody::LinkConstPtr&)’
>              query->report->vLinkColliding.push_back(query->report->plink2);
>                                                                           ^
> /home/tomas/or_fcl/src/FCLCollisionChecker.cpp:847:74: note: candidates are:
> In file included from /usr/include/c++/4.8/vector:64:0,
>                  from /usr/include/c++/4.8/bits/random.h:34,
>                  from /usr/include/c++/4.8/random:50,
>                  from /usr/include/c++/4.8/bits/stl_algo.h:65,
>                  from /usr/include/c++/4.8/algorithm:62,
>                  from /usr/include/boost/iterator/iterator_concepts.hpp:29,
>                  from /usr/include/boost/range/concepts.hpp:20,
>                  from /usr/include/boost/range/algorithm/equal.hpp:14,
>                  from /usr/include/boost/range/iterator_range_core.hpp:31,
>                  from /usr/include/boost/range/iterator_range.hpp:13,
>                  from /usr/include/boost/range/adaptor/transformed.hpp:15,
>                  from /usr/include/boost/range/adaptor/map.hpp:14,
>                  from /home/tomas/or_fcl/src/FCLCollisionChecker.cpp:32:
> /usr/include/c++/4.8/bits/stl_vector.h:901:7: note: void std::vector<_Tp, _Alloc>::push_back(const value_type&) [with _Tp = std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> >; _Alloc = std::allocator<std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> > >; std::vector<_Tp, _Alloc>::value_type = std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> >]
>        push_back(const value_type& __x)
>        ^
> /usr/include/c++/4.8/bits/stl_vector.h:901:7: note:   no known conversion for argument 1 from ‘OpenRAVE::KinBody::LinkConstPtr {aka boost::shared_ptr<const OpenRAVE::KinBody::Link>}’ to ‘const value_type& {aka const std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> >&}’
> /usr/include/c++/4.8/bits/stl_vector.h:919:7: note: void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> >; _Alloc = std::allocator<std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> > >; std::vector<_Tp, _Alloc>::value_type = std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> >]
>        push_back(value_type&& __x)
>        ^
> /usr/include/c++/4.8/bits/stl_vector.h:919:7: note:   no known conversion for argument 1 from ‘OpenRAVE::KinBody::LinkConstPtr {aka boost::shared_ptr<const OpenRAVE::KinBody::Link>}’ to ‘std::vector<std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> > >::value_type&& {aka std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> >&&}’
> In file included from /usr/include/boost/smart_ptr/make_shared.hpp:15:0,
>                  from /usr/include/boost/make_shared.hpp:15,
>                  from /home/tomas/or_fcl/src/FCLCollisionChecker.cpp:34:
> /usr/include/boost/smart_ptr/make_shared_object.hpp: In instantiation of ‘typename boost::detail::sp_if_not_array<T>::type boost::make_shared(Arg1&&, Args&& ...) [with T = fcl::CollisionObject; Arg1 = const boost::shared_ptr<fcl::CollisionGeometry>&; Args = {}; typename boost::detail::sp_if_not_array<T>::type = boost::shared_ptr<fcl::CollisionObject>]’:
> /home/tomas/or_fcl/src/FCLCollisionChecker.cpp:764:72:   required from here
> /usr/include/boost/smart_ptr/make_shared_object.hpp:218:5: error: no matching function for call to ‘fcl::CollisionObject::CollisionObject(const boost::shared_ptr<fcl::CollisionGeometry>&)’
>      ::new( pv ) T( boost::detail::sp_forward<Arg1>( arg1 ), boost::detail::sp_forward<Args>( args )... );
>      ^
> /usr/include/boost/smart_ptr/make_shared_object.hpp:218:5: note: candidates are:
> In file included from /usr/local/include/fcl/collision.h:43:0,
>                  from /home/tomas/or_fcl/src/FCLCollisionChecker.cpp:37:
> /usr/local/include/fcl/collision_object.h:171:3: note: fcl::CollisionObject::CollisionObject(const std::shared_ptr<fcl::CollisionGeometry>&, const Matrix3f&, const Vec3f&)
>    CollisionObject(const std::shared_ptr<CollisionGeometry> &cgeom_, const Matrix3f& R, const Vec3f& T):
>    ^
> /usr/local/include/fcl/collision_object.h:171:3: note:   candidate expects 3 arguments, 1 provided
> /usr/local/include/fcl/collision_object.h:164:3: note: fcl::CollisionObject::CollisionObject(const std::shared_ptr<fcl::CollisionGeometry>&, const fcl::Transform3f&)
>    CollisionObject(const std::shared_ptr<CollisionGeometry> &cgeom_, const Transform3f& tf) :
>    ^
> /usr/local/include/fcl/collision_object.h:164:3: note:   candidate expects 2 arguments, 1 provided
> /usr/local/include/fcl/collision_object.h:154:2: note: fcl::CollisionObject::CollisionObject(const std::shared_ptr<fcl::CollisionGeometry>&)
>   CollisionObject(const std::shared_ptr<CollisionGeometry> &cgeom_) :
>   ^
> /usr/local/include/fcl/collision_object.h:154:2: note:   no known conversion for argument 1 from ‘const boost::shared_ptr<fcl::CollisionGeometry>’ to ‘const std::shared_ptr<fcl::CollisionGeometry>&’
> /usr/local/include/fcl/collision_object.h:151:7: note: fcl::CollisionObject::CollisionObject(const fcl::CollisionObject&)
>  class CollisionObject
>        ^
> /usr/local/include/fcl/collision_object.h:151:7: note:   no known conversion for argument 1 from ‘const boost::shared_ptr<fcl::CollisionGeometry>’ to ‘const fcl::CollisionObject&’
> make[2]: *** [CMakeFiles/or_fcl_plugin.dir/src/FCLCollisionChecker.cpp.o] Error 1
> make[1]: *** [CMakeFiles/or_fcl_plugin.dir/all] Error 2
> make: *** [all] Error 2`

#### I install or_fcl this way:

> git clone https://github.com/flexible-collision-library/fcl.git
> mkdir -p or_fcl/build
> cd or_fcl/build
> cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CATKIN:bool=0 ..
> make

#### This is my log from cmake:

> -- The C compiler identification is GNU 4.8.4
> -- The CXX compiler identification is GNU 4.8.4
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
> -- Boost version: 1.54.0
> -- Found the following Boost libraries:
> --   system
> CMake Warning at CMakeLists.txt:13 (find_package):
>   By not providing "Findfcl.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "fcl", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "fcl" with any of
>   the following names:
> 
>     fclConfig.cmake
>     fcl-config.cmake
> 
>   Add the installation prefix of "fcl" to CMAKE_PREFIX_PATH or set "fcl_DIR"
>   to a directory containing one of the above files.  If "fcl" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> 
> -- checking for module 'fcl'
> --   found fcl, version 0.5.0
> -- Performing Test HAVE_REPORT_VLINKCOLLIDING_PAIR
> -- Performing Test HAVE_REPORT_VLINKCOLLIDING_PAIR - Failed
> -- Checking for C++11 compiler
> -- Checking for C++11 compiler - available
> -- Building without Catkin.
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/tomas/or_fcl/build

**Comment by cdellin** [comment] 2016-03-31 17:20
Note that this is a duplicate of the email exchange [here](http://openrave-users-list.185357.n3.nabble.com/or-fcl-FCL-collision-checking-plugin-for-OpenRAVE-td4027746.html).  I'm moving the discussion to this issue.

As I mentioned in my first response, your original problem was due to a problem with the `HAVE_REPORT_VLINKCOLLIDING_PAIR` configuration-time check.

In the meantime, it looks like you attempted to try against the latest development version of FCL.  Unfortunately, they recently introduced a [change](https://github.com/flexible-collision-library/fcl/commit/9703a24) to use C++11 constructs, which is currently incompatible with `or_fcl`.  I've made an issue (#18) to track this, but for now, please only used a released version of FCL (e.g. [version 0.4.0](https://github.com/flexible-collision-library/fcl/tree/0.4.0)).

To debug the original issue, it appears from your error message:

    or_fcl/src/FCLCollisionChecker.cpp:847:74: error: no matching function for call to ‘std::vector<std::pair<boost::shared_ptr<const OpenRAVE::KinBody::Link>, boost::shared_ptr<const OpenRAVE::KinBody::Link> > >::push_back(OpenRAVE::KinBody::LinkConstPtr&)’

That your version of OpenRAVE should pass the `HAVE_REPORT_VLINKCOLLIDING_PAIR` check, but it looks from your CMake output that the check either wasn't being performed, or it is failing.  I understand that you attempted to force the check to succeed by modifying the `CMakeLists` file like this:

    #if (HAVE_REPORT_VLINKCOLLIDING_PAIR)
      add_definitions(-DHAVE_REPORT_VLINKCOLLIDING_PAIR)
    #endif ()

By making this modification and re-building `or_fcl` (from scratch, that is, removing any `CMakeCache.txt` and `CMakeFiles` files/directories), you should no longer see the error.  If you're still seeing the error, try the following command to get a more verbose output:

    make VERBOSE=1

**Comment by Softwaretom007** [comment] 2016-04-01 08:20
Thanks for advice !
So i compile 0.4.0 version of fcl. Clear all cache in or_fcl and comment if (HAVE_REPORT_VLINKCOLLIDING_PAIR). and endif().
cmake still report Performing Test HAVE_REPORT_VLINKCOLLIDING_PAIR - Failed
but make works ! 
I had to use sudo make install. Only make install not work : 
> Installing: /usr/local/share/openrave-0.9/plugins/or_fcl_plugin.so
> CMake Error at cmake_install.cmake:42 (file):
>   file INSTALL cannot copy file "/home/tomas/or_fcl/build/or_fcl_plugin.so"
>   to "/usr/local/share/openrave-0.9/plugins/or_fcl_plugin.so".

Next I had error while I try to use fcl
> [plugindatabase.h:577 Create] Failed to create name fcl, interface collisionchecker
This command not work:
> export OPENRAVE_PLUGINS="/usr/local/share/openrave-0.9/plugins:${OPENRAVE_PLUGINS}"

So i copy to  `/usr/local/lib/openrave0.9-plugins` this libraries: `or_fcl_plugin.so , libfcl.so, libfcl.so.0.4.0, libfcl.so.6 , libfcl.so.7`
(If I copy only plugin, it wont work because other libs not found).

Now everything works, and computations are 3 times faster ! 
Now I will be waiting for updates and bug fixes. 
Thanks a lot.

**Comment by cdellin** [comment] 2016-04-02 00:06
Glad to hear everything is working. Yes, if you install FCL from source as you have, then you also need to make sure FCL's libraries can be located when OpenRAVE loads the `or_fcl` plugin.  I'm closing this issue -- feel free to open a new issue here if you have more problems.

**Closed by cdellin** 2016-04-02 00:06 UTC
